-- MySQL Script generated by MySQL Workbench
-- Mon Jan 29 15:20:45 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_kasir
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_kasir
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_kasir` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_kasir` ;

-- -----------------------------------------------------
-- Table `db_kasir`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kasir`.`customers` (
  `id_customers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` TEXT NOT NULL,
  `phone` INT NOT NULL,
  PRIMARY KEY (`id_customers`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_kasir`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kasir`.`products` (
  `id_products` INT NOT NULL AUTO_INCREMENT,
  `name_products` VARCHAR(200) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `stock` INT NULL DEFAULT '0',
  `entry_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_products`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_kasir`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kasir`.`stocks` (
  `id_stock` INT NOT NULL AUTO_INCREMENT,
  `id_product` INT NOT NULL,
  `stock_quantity` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_stock`),
  INDEX `id_product` (`id_product` ASC) VISIBLE,
  CONSTRAINT `stocks_ibfk_1`
    FOREIGN KEY (`id_product`)
    REFERENCES `db_kasir`.`products` (`id_products`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_kasir`.`transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kasir`.`transactions` (
  `id_transactions` INT NOT NULL AUTO_INCREMENT,
  `id_customers` INT NULL DEFAULT NULL,
  `transaction_date` DATE NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `purchase_date` DATE NOT NULL,
  PRIMARY KEY (`id_transactions`),
  INDEX `id_customers` (`id_customers` ASC) VISIBLE,
  CONSTRAINT `transactions_ibfk_1`
    FOREIGN KEY (`id_customers`)
    REFERENCES `db_kasir`.`customers` (`id_customers`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_kasir`.`transactions_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_kasir`.`transactions_details` (
  `id_detail` INT NOT NULL AUTO_INCREMENT,
  `id_transactions` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL DEFAULT '0',
  `total_price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detail`),
  INDEX `id_transactions` (`id_transactions` ASC) VISIBLE,
  INDEX `id_product` (`id_product` ASC) VISIBLE,
  CONSTRAINT `transactions_details_ibfk_1`
    FOREIGN KEY (`id_transactions`)
    REFERENCES `db_kasir`.`transactions` (`id_transactions`),
  CONSTRAINT `transactions_details_ibfk_2`
    FOREIGN KEY (`id_product`)
    REFERENCES `db_kasir`.`products` (`id_products`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
